######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 26 12:15:20 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += calc.ui
SOURCES += main.cpp mainwindow.cpp
